update compile action

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -56,7 +56,8 @@ jobs:
       run: |
         python -m pip list
     - name: Setup TeX Live
-      uses: teatimeguest/setup-texlive-action@v3
+      # uses: teatimeguest/setup-texlive-action@v3
+      uses: zauguin/install-texlive@v4
       with:
         # version: 2024
         # List of TeXLive-packages contained in the scheme-small
@@ -250,6 +251,13 @@ jobs:
           helvet
           dvips
           urw
+    - name: Verify helvetic
+      run: |
+        echo "[Before compile] Check helvetic"
+        tlmgr info helvetic
+        echo "-- locate phvb7t.tfm (should NOT be empty)"
+        tlmgr search --file --global phvb7t.tfm || true
+        kpsewhich phvb7t.tfm || (echo "phvb7t.tfm still missing" && exit 1)
     - name: Install latexmk and extra software
       run: |
         sudo apt install -y latexmk \
